### ISSUE TITLE
Dark mode Probleme

### ISSUE THREAD

**Issue by xeruf** [stonecrusher/stylus-UserCSS#1]
![image](https://user-images.githubusercontent.com/13354331/43741121-a132dcee-99cd-11e8-8045-1a0d310d8da0.png)

![image](https://user-images.githubusercontent.com/13354331/43741148-b0045266-99cd-11e8-98b8-2e4a9570ed3d.png)

Nur ein paar kleine Sachen die gefixt werden müssten ;)

**Comment by stonecrusher** [comment]
Danke für die Meldung.

Filterregeln korrigiert.

Logout geht schlecht zu beheben, da das alles in einem Hintergrundbild steckt und das könnte ich höchstens invertieren, gibt aber eklige braun-türkise Farben.

Habe jetzt per `::before` einfach die Überschrift hinzugefügt.
