### ISSUE TITLE
Modifications of gmx webmail

### ISSUE THREAD

**Issue by Procyon-b** [stonecrusher/stylus-UserCSS#11]
style: "GMX FreeMail ausgeputzt"

Hi, I'm not using your userstyle very often - only as a fallback for my own stylesheet when something breaks - but maybe I can help you fix some issues.

For several weeks now, gmx has added a new ad-slot in the email listing. With a good adblocker, no ad is shown but a blank entry still appears. I'm targeting the element with this selector: `tr[data-component-pixelurls*="adfarm1"]`. (you can also target it more precisely with `#mail-list tr[data-component-pixelurls*="adfarm1"]` but I haven't tested it on all gmx sites)

In july 2020 they changed the styling of the mail listing button's bar to match what appeared on web.be (gray). I had a local copy of a gmx page with the previous style and I was able to restore it. It is downloadable on greasyfork (I also have there a couple of userscripts for gmx webmail) if you want to look at it. `https://greasyfork.org/en/scripts/411899-gmx-webmails-restore-blue-buttons-bar` It has been updated to work with the current design of the buttons.
Unfortunately I only had a copy for their default style '.theme-intenseblue', not for the others.

**Comment by stonecrusher** [comment]
Hi, thanks for the hint. I'm not using it myself and don't know if something breaks. Made it years ago for a friend I'm not in contact with anymore.

I made an [update](https://github.com/stonecrusher/stylus-UserCSS/commit/1d824c579ebb9e579e556b0d40246d7826d91313), please check if it's better now. Couldn't see the ad you are talking about, but I didn't want to disable all the blocking stuff I have installed.

The styling aspect fell short after their big redesign, so no more darkstyle and I won't implement the old button style.
It's just about making it more clean and safer for older folks who are overwhelmed with stuff to click on.

Nevertheless, you're welcome to make PRs, fork, tell me about issues.
Thanks!

**Comment by Procyon-b** [comment]
I was previously using a program to handle my email, and I would still be using it if I had to deal with gmail or hotmail. But gmx's interface is quite clean, and with the help of some userstyles and userscripts it's really nice to use. Losing contact with friends is the sad thing nowadays. Especially when it's so easy today to stay in touch by emails. I've lost quite a few in the past 10 years.

Here is how it looks without adblocking and userstyle:
![cap-gmx](https://user-images.githubusercontent.com/40043075/117830348-d5a0cb00-b273-11eb-875e-b9f74745f499.gif)

The first ad-slot has been modified and is now serving google ads.

This how it looked with ublock and you userstyle:
![cap-gmx3](https://user-images.githubusercontent.com/40043075/117831115-91fa9100-b274-11eb-8ac6-0916515e3169.gif)

And with the current version of your userstyle:
![cap-gmx4](https://user-images.githubusercontent.com/40043075/117831261-b0608c80-b274-11eb-9e37-ddd025e8cc91.gif)


The old button style is just a matter of colors. Nothing else. (see `https://procyon-b.github.io/programming/#gmx_toolbar`)
What is broken in their new style regarding the dark mode?

**Comment by stonecrusher** [comment]
So looking at your last screenshot I think it's good now, is it?

I will eventually remove the darkstyle. Not worth the effort anymore as https://darkreader.org/ does a good job here.

If it makes your life easier, I can copy your code for blue buttons and insert it as option.

Offtopic: I also prefer a long email to that dull "Hey how is it going?"-mobile messenger chat ping-pong. Good choice ;-)

**Comment by Procyon-b** [comment]
Yes, it works now.
I don't use the darkstyle. I was just wondering what had happened.
I was just offering the code for blue buttons (since I had their original stylesheet saved). As I said above, I'm using your stylesheet only as a backup. I have my own (private) stylesheet implementing other minor changes (a margin here, a margin there).
I came here after reading (translating) the warning about darkstyle in the latest version of your stylesheet. Since the ad-slot was still visible, I came to warn you.

**Comment by stonecrusher** [comment]
Thank you for your effort.
I just removed darkstyle remnants and matched gmx.net and web.de styles as they are almost the same.
Didn't insert the old button code because it's quite convenient that you already put it on greasyfork as a separate style. So the user can install both side by side and doesn't suffer me lagging behind your updates on the blue button style.

First I planned to rewrite the dark style, but darkreader became better and better and so only the notice remained.

**Comment by Procyon-b** [comment]
I almost never use dark mode anywhere. But I don't push screen brightness that much compared to some people.
Lately I've started using it on youtube and 9gag when my eyes are a little tired at night.

By the way, beyond gmx.net and web.be, the gmx pool of international sites contains (as far as I know): gmx.net, gmx.com, gmx.fr, gmx.es, gmx.co.uk, gmx.at, gmx.ch, web.de. I'll have to verify .at and .ch. At some point in the past they where redirecting to the gmx.net domain after log in.
Except for web.de which theme is gray, all the other use the default blue theme. My userscripts and styles have been tested on them and work correctly.

**Comment by stonecrusher** [comment]
I just checked the landing pages (don't know about logged in):
```
Main page:                    gmx.net
Redirect to gmx.net:          gmx.de
No redirect, but same:        gmx.at, gmx.ch
Slightly different structure: gmx.com, gmx.fr, gmx.co.uk, gmx.es
```
Doesn't seem to have changed much since I made the style years ago. I think just .co.uk and .es are "new".

**Comment by Procyon-b** [comment]
Apart from the homepage (simplified is some cases), the webmail interface is identical on all these sites.
I've verified .ch and .at with my test accounts, and once identified they use `navigator.gmx.net` for the webmail interface. All the other national TLDs stay on the same tld.

So, for every styling related to the webmail (top button bar, email ad-slot, ...) your userstyle can handle them like gmx.net without any modification.
