### ISSUE TITLE
GMX: After logout, the site is empty. Should show Login button.

### ISSUE THREAD

**Issue by Mihaeru** [stonecrusher/stylus-UserCSS#13]
I'm using the GMX style in version 4.0.3. As mentioned in the title, after logout, screen is empty. When disabling the GMX style, a 'Back to login' button is displayed at the top of the page:
`<div data-component="icon" data-pre-icon=""><svg viewBox="0 0 20 20" data-type="success"><path d="M10,0A10,10,0,1,0,20,10,10,10,0,0,0,10,0Zm6.186,7.083L9.648,13.622h0L8.587,14.683h0a0.5,0.5,0,0,1-.707,0L6.817,13.624l-0.005-.008-3-3a0.5,0.5,0,0,1,0-.707L4.874,8.85a0.5,0.5,0,0,1,.707,0L8.233,11.5l6.186-6.186a0.5,0.5,0,0,1,.707,0l1.061,1.061A0.5,0.5,0,0,1,16.186,7.083Z"></path></svg></div><div data-text=""><strong>Sie haben sich erfolgreich ausgeloggt.</strong>&nbsp; <span>Vielen Dank für Ihren Besuch bei GMX!</span></div><div data-buttons=""><a data-component="button" href="https://www.gmx.net/" data-importance="accent"> Zurück zum Login </a></div>
`
![image](https://user-images.githubusercontent.com/36927696/170192826-2cd1a828-5c22-44d8-b8cb-2f36f266213c.png)

URL is https://www.gmx.net/logoutlounge/...

My browser is Firefox 100.0.2 with uBlock origin activated (but no difference when I disable uBlock for this site)

Besides this, great work and many thanks!!

**Comment by stonecrusher** [comment]
Hey,
thanks for the notice as I don't really use the style anymore, thus don't maintain properly.

Gave it an update, please see if works for you.

By the way I recommend an auto-redirect script to make things more comfortable.
Install with tampermonkey or greasemonkey or similar addon:

```
// ==UserScript==
// @name         GMX redirect after logout
// @namespace    graphen
// @version      2.1.1
// @description  From logout lounge to main page
// @author       Graphen
// @match        https://www.gmx.net/logoutlounge/*
// @match        https://www.gmx.net/?status=session-expired
// @match        https://www.gmx.net/consent-management/*
// @match        https://www.gmx.net/fairplay/*
// @grant        none
// @noframes
// @run-at       document-start
// ==/UserScript==

/* jshint esversion: 6 */
(function (doc) {
    'use strict';

    function redirect() {
        window.location.replace("https://www.gmx.net/?origin=lpc");
    }

    setTimeout(redirect(), 500);

})(document);

```

**Comment by Mihaeru** [comment]
Great! Thanks a lot! I don't us the GMX webmail very often but sometimes I want to declare some mail as spam or non-spam and then I really appreciate the GMX style usage.
Also thanks for the recommendation of the auto-redirect. I will try that out.
