### ISSUE TITLE
web.de: login page with some new ad above the input form (in my case "Allianz")

### ISSUE THREAD

**Issue by dumblob** [stonecrusher/stylus-UserCSS#14]
Today an ad "rectangle" started to show up above the login input form.

## Screenshot(s)

![20221129_095907+0100-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/204487019-59d9a99c-83e3-41c2-af8f-8308c7c56896.png)

## Additional information
- Operating System: Arch Linux
- Browser + version:  Chromium 107.0.5304.121
- CSS extension + version: Stylus 1.5.22

**Comment by stonecrusher** [comment]
Hi!
Wir können gerne zu deutsch wechseln.
Ich kann es gerade leider nicht reproduzieren, vielleicht wird es erst ausgerollt.

Ich habe testweise meine Blocker deaktivieret:
1. [Pi-Hole](https://pi-hole.net/)
2. [uBlock Origin](https://ublockorigin.com/)
3. Umleitung zu `https://web.de/?origin=lpc` um der Cookieabfrage zu entgehen
    <details><summary>Tampermonkey skript</summary>

        // ==UserScript==
        // @name         WEB.DE redirect after logout
        // @namespace    graphen
        // @version      2.0.0
        // @description  From logout lounge to main page
        // @author       Graphen
        // @match        https://web.de/logoutlounge/*
        // @match        https://web.de/?status=session-expired
        // @match        https://web.de/consent-management/*
        // @grant        none
        // @noframes
        // ==/UserScript==
        
        /* jshint esversion: 6 */
        (function (doc) {
            'use strict';
        
            function redirect() {
                window.location.replace("https://web.de/?origin=lpc");
            }
        
            setTimeout(redirect(), 500);
        
        })(document);

</summary>

Kommt trotzdem (noch) nichts.

Muss ich leider erst mal so stehen lassen.  
Die Login-Leiste sollte eigentlich auch weiter oben sein, wird vermutlich durch den Anzeigen-Platzhalter nach unten geschoben.

Evtl könntest du mal mit Rechtsklick auf "Anzeige", dann "Objekt untersuchen" und dann einen Screenshot von dem Quelltext, der da kommt.

p.s.: Muss gestehen, habe es noch nicht mit Chromium versucht (nur Firefox), ich denke heute abend / morgen schaffe ich das

**Comment by dumblob** [comment]
Ist nichts extrem wichtiges, nimm dir Zeit. Hier kommt das Screenshot des Quelltextes:

![20221129_115741+0100-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/204512357-a69dc90a-da89-4950-8483-85bdb785bd8b.png)

Ich habe das jetzt mehrmals getestet und kann sagen, dass die Anzeige erst nach einigen Sekunden oder noch später vorkommt.

**Comment by stonecrusher** [comment]
Ein Schuss ins Blaue:  
Probier einfach mal, die Zeile 28
```
html > body > #app > .main > .main-content > div,
```
mit
```
html > body > #app > .main > .main-content > div[data-content],
```
im Style zu ersetzen.

könnte aber sein, dass dann auch (warn)hinweise ausgeblendet werden (z.B. bei fehlgeschlagenem login).

**Comment by stonecrusher** [comment]
Habe es einfach mal übernommen. Schau bitte, ob es bei dir weg ist.
