### ISSUE TITLE
Wrong Text-Color on Shipping Information

### ISSUE THREAD

**Issue by psschn** [stonecrusher/stylus-UserCSS#15]
Issue: Wrong Text color in Shipping Instruction for Amazon Hub Locker-Orders
Style: 
`@name           Amazon Stony Dark
@namespace      Stonecrusher
@author         Stonecrusher
@version        1.13.13
@homepageURL    https://github.com/stonecrusher/stylus-UserCSS/tree/master/amazon
@supportURL     https://github.com/stonecrusher/stylus-UserCSS/issues
@updateURL      https://userstyles.world/api/style/4809.user.css
@license        CC-BY-NC-SA-4.0
@preprocessor   stylus`
Style-Version from Userstyles.world via Stylus

I have taken an Order which goes to an Amazon Locker. The Shipping Information, which tell you that you need the App to open the Locker is in a really dark teal green (#002F36) by default. This CSS does not Change the default color, so the text is barely visible. I have already fixt this in my Copy of the Style by adding the following code to the CSS and change the color to a better Teal Green (#50cbdd).

`.desktop #shippingAddress-container .shipOdin-instruction, .tablet #shippingAddress-container .shipOdin-instruction {
    color: #50cbdd;
}`

It is not a perfect Fix, but it does what is needed to do and works for me. This for your Information for inplement this in the next version.

## Screenshot(s)
before:
![image](https://user-images.githubusercontent.com/118092749/207854637-49e61f3c-501b-4a3a-95b0-0e40feb02a99.png)
after:
![image](https://user-images.githubusercontent.com/118092749/207854798-29027d9d-8a87-4379-a7a7-c293537e33ba.png)

## Additional information
- Operating System: Linux Mint 21.0
- Browser + version:  Vivaldi (Chrome-based)  5.6.2867.40 (Stable channel) stable (64-Bit) 
- CSS extension + version: Stylus 1.5.26

**Comment by psschn** [comment]
Other than that though, very good job with the theme. It seems everything has been considered that needs to be adjusted on this very crowded website to achieve such a result. It is a "revelation" for the eyes, especially for spontaneous night buying decisions.

**Comment by stonecrusher** [comment]
Hi!  
Well I can't reproduce it as I don't have any locker hubs nearby and never used that feature. But it's no problem, I'll just trust you. Thank you for the detailed information!

Overall I am neglegting the maintenance of this amazon style more and more, but I will fix things as long as they aren't too big of a change.  
The style should be rewritten from scratch, adopting to the amazon style principles. It just grew over the years, using the site and wildly inserting fixes as I come across the little bugs.

I still use the style as I find [dark reader's](https://darkreader.org/) automatic stuff doesn't always meet my expectations. Maybe that will change in the future. However I can only recommend that awesome addon!

https://github.com/stonecrusher/stylus-UserCSS/commit/c0601a1cdd26d6299c52ce941b4cd50560d9f268
