### ISSUE TITLE
amazon dark not working on Author site

### ISSUE THREAD

**Issue by arogl** [stonecrusher/stylus-UserCSS#16]
- Language: English
- Tell which style the issue is about: Amazon
- Tell if you use the UserCSS version from Github

[x] Make sure you use the latest version of the style

On author pages, still large amounts of white screen

[Amazon.com: BookSumo Press: books, biography, latest update](https://www.amazon.com/stores/author/B01HYJPSHY)

## Screenshot(s)
![Amazon com_ BookSumo Press_ books, biography, latest update](https://user-images.githubusercontent.com/1115472/230519229-bc5f3486-5e53-43d2-b7b2-64fead1c8c62.png)

## Additional information
- Operating System: Windows 10 x64
- Browser + version:  Chrome Version 112.0.5615.50 (Official Build) (64-bit), Firefox 111.0.1 (64-bit)
- CSS extension + version: Stylus (beta) 1.5.30, Stylus 1.5.29

**Comment by stonecrusher** [comment]
Oh wow, that's flashy.
Unfortunately programmatically the site seems to come from the old amazon pages and is very tedious to work with.
See if the update to 1.14.2 works for you.
Note that at this point I'm not "styling" it, just un-flash and keep things readable.

Thank you for the detailed report.

**Comment by arogl** [comment]
@stonecrusher Thanks for the quick update, looks much better.
