### ISSUE TITLE
A few more tweaks on Amazon books

### ISSUE THREAD

**Issue by arogl** [stonecrusher/stylus-UserCSS#17]
On the first link the dropdown is still white, on the second it is styled:

[Shuk Institute: books, biography, latest update](https://www.amazon.com/stores/Shuk-Institute/author/B0BGJQ2MGG/allbooks?isDramIntegrated=true&shoppingPortalEnabled=true)

[TOM RUELL: Kindle store](https://www.amazon.com/s?i=digital-text&rh=p_27%3ATOM++RUELL&s=price-asc-rank&qid=1680909608&text=TOM++RUELL&ref=sr_st_price-asc-rank&ds=v1%3AX9l96moZfkkZu%2FdWpoavhS6qvvM5HJQUoW0rFQwhTMY)

## Screenshot(s)

![Dropdown](https://user-images.githubusercontent.com/1115472/230691614-9c0b80aa-32ef-4a56-bd32-73eaa9884895.png)

![Dropdown](https://user-images.githubusercontent.com/1115472/230691815-66ea5fcf-af86-47fc-9491-c38c540975ac.png)

## Additional information
- Operating System: Windows 10 x64
- Browser + version:  Chrome Version 112.0.5615.50 (Official Build) (64-bit)
- CSS extension + version: Stylus 1.3.0

**Comment by stonecrusher** [comment]
Please check the new version.

**Comment by arogl** [comment]
Thank you, that seems to have fixed it.

Time to learn html/css a lot better than my guessing
