### ISSUE TITLE
Add Customization to Product Backgrounds

### ISSUE THREAD

**Issue by Devo7v** [stonecrusher/stylus-UserCSS#2]
I am using v1.10.13 installed from GitHub into Stylus

Would it be possible to customize the color of the light grey area surrounding the products (see screenshot)?  I have no other styles or extensions effecting the site.
## Screenshot
![alt text](https://i.imgur.com/1b9qsp2.png "Amazon Screenshot")
## Additional information
- Operating System: **Windows 10 x64**
- Browser + version:  **Firefox 71.0**
- CSS extension + version: **Stylus 1.5.6**

**Comment by stonecrusher** [comment]
There's no separate option for that.
Make a new style with the following code:
```
/* ==UserStyle==
@name           Amazon Stony Dark Companion style
@namespace      Stonecrusher
@version        1.0.0
@license        unlicense
@description    Change product card background
==/UserStyle== */

@-moz-document regexp("https?:\\/\\/(www|music|smile)\\.amazon\\.(cn|in|co\\.jp|sg|fr|de|it|nl|es|co\\.uk|ca|com(\\.(mx|au|br))?)\\/.*") {
    .gw-card-layout .a-cardui {
        background-color: green !important;
    }
}
```
You can change the "green" to whatever RGB value you want.

**Comment by Devo7v** [comment]
I understand that, I guess I'm asking if you could make that configurable within your style.  You could add another variable to the top:
`@var color     var_bg3          'DS Light Background'       #6f6f6f`

And then just comment out line #38.

Also while I'm looking at it, it might make sense to remove `#pageContent hr` from line #445.  It simply acts as a divider between the different sections and it looks a little cleaner without it.

I understand and appreciate that I can make a companion style to address this, but I was thinking that the additional customization might just be a simple tweak that would benefit all users.

**Comment by stonecrusher** [comment]
> it might make sense to remove #pageContent hr from line #445. It simply acts as a divider

I'll give it a try. As far as I remember this wasn't meant for the main page anyway. Some other site has lost recognizable dividers now, but whatever, you'll probably see the mainpage much more often.
https://github.com/stonecrusher/stylus-UserCSS/commit/75e97026362061098c4619b3f27710f5cfa65962

> I'm asking if you could make that configurable

The main idea here was to be able to change the whole appearance by choosing a single color. Like "make everything greenish". That will be lost if I make a separate option. And the options menu even gets longer...
That color is used 24 times in the style and only god knows at which places. Could affect button shadows or whole sidebar-blocks.
As I use the default colors, there will probably be more errors if you change them, especially regarding contrast. But I'll get to that if someone reports. No time for extensive testing.

Maybe there is a solution via stylus-language's `if` construct? Or via Stylus' setting a variable as default color? I think I remember some guys do something similar with default background images (only change it if user customizes).
Looking at [the](https://github.com/openstyles/stylus/wiki/UserCSS-authors#default-value) [wiki](https://github.com/openstyles/stylus/wiki/UserCSS-authors#variable-examples) I don't think it's possible.

The thing is, where to stop? I use those further bg colors quite inconsequently and free ("hmm looks too dark, let's try the var_bg with next higher number").
Should var_bg4 derive from var_bg3 or from var_bg1?
I'm not totally against a change, just need a little thought over it.

**Comment by stonecrusher** [comment]
I had another look on it and I think the best solution is if you just create a [companion style](https://github.com/stonecrusher/stylus-UserCSS/issues/2#issuecomment-567549646) so you won't have update problems.
I can't really spot the disadvantages in that solution.
