### ISSUE TITLE
Amazon UserCSS Header URL

### ISSUE THREAD

**Issue by Devo7v** [stonecrusher/stylus-UserCSS#3]
The following links should be added/updated in the header in the amazon usercss
`@homepageURL    https://github.com/stonecrusher/stylus-UserCSS/tree/master/amazon`
`@updateURL      https://raw.githubusercontent.com/stonecrusher/stylus-UserCSS/master/amazon/amazon.user.css`

Right now the homepage points to an invalid URL and there is no update URL so Stylus cannot update the style manually.

**Comment by stonecrusher** [comment]
Thanks for the hint.
Defining an updateURL actually [shouldn't be necessary](https://github.com/openstyles/stylus/wiki/UserCSS-authors#updateurl):

> otherwise the style is updated from where it was installed.

but I guess you installed the style quite long ago when the url hadn't changed yet.

Fixed: 9cded79296e4be1eaaf9966bb5104a156e6c2630
