### ISSUE TITLE
gmx-geputzt.user.css - Preview pdf attachment is not possible

### ISSUE THREAD

**Issue by ddesch** [stonecrusher/stylus-UserCSS#4]
I'm using the UserCSS version from Github (https://raw.githubusercontent.com/stonecrusher/stylus-UserCSS/master/gmx/gmx-geputzt.user.css) version: 2.3.3

When I click on the attachment and on "show" it doesn't load the GMX pdf viewer.
The browser console shows the following error:
offsetParent is not set -- cannot scroll pdf.viewer.js:formatted:19499

I was able to solve the problem by commenting out the line 189:
/*.atl-third-party-dialog__blocker,*/ /* Neues Overlay 2018-03 */

But I don't know if that's the best solution...

## Additional information
- Operating System: Windows 10 x64
- Browser + version:  Firefox 71.0 (64-Bit)
- CSS extension + version: Stylus 1.5.6

**Comment by stonecrusher** [comment]
Thank you for the report.
Hmm indeed, I can reproduce.

> I don't know if that's the best solution...

For now, it is.  
First, that "new" overlay probably blocked some 2018 easter campaign or whatever which is obsolete now.
Second, the fact that there is a dated annotation shows that the CSS selector is a bit too indistinct and I left the annotation in case something breaks.

https://github.com/stonecrusher/stylus-UserCSS/commit/8b662d57a14d8f180ebf5ff3670851861570eeca
