### ISSUE TITLE
"Clean web.de" style doesn't work anymore

### ISSUE THREAD

**Issue by KaiRoesnerAtSAP** [stonecrusher/stylus-UserCSS#5]
- Using the "web.de komplett geputzt - Login, Logout, Werbung" style
- Using UserCSS version from Github
- Using version v2.3.9 of the style

While it's been working fine unitl the last update, now the style does not do anything anymore - cf. screenshot

## Screenshot(s)
![web_de_login_page](https://user-images.githubusercontent.com/43342031/75430146-341daa00-594b-11ea-86e9-1ff88ea21392.jpg)

## Additional information
- Operating System: Windows 10 x64
- Browser + version:  Firefox 73.0.1
- CSS extension + version: Stylus 1.5.6

**Comment by stonecrusher** [comment]
Ugh, can confirm. Thanks for the notice.
It's an update on their side which needs (a probably big update) from my side.
I hope I'll find time for this today. In the meantime you need to disable the style temporarly :-/

**Comment by stonecrusher** [comment]
Update your version to 3.0.0 to receive the "emergency rewrite".
I'm happy if you report further bugs / feature requests.
Kann auch auf deutsch sein :-)

**Comment by KaiRoesnerAtSAP** [comment]
Everything nice and clean again - thanks for the quick action!
In Zukunft dann auf deutsch...
