### ISSUE TITLE
Ebay Kleinanzeigen Chat Anzeigenname

### ISSUE THREAD

**Issue by truresma** [stonecrusher/stylus-UserCSS#8]
- Language: German
- Ebay Kleinanzeigen Chat Anzeigenname
- GitHub Kleinanzeigen Dark v3.6.4

Ebay Kleinanzeigen Chat Bug, Anzeigenname ist schlecht lesbar.

**Comment by stonecrusher** [comment]
Hi,
danke für die Rückmeldung.
Also eigentlich ist das nicht schlecht lesbar?
![2020-10-12 18_15_07-](https://user-images.githubusercontent.com/1388389/95768855-47ea0680-0cb7-11eb-899e-e83658a9d6dc.png)
Du kannst in den Styleoptionen einfach die Linkfarbe von hellblau nach z.B. orange verändern, dann werden auch die Farben der Namen geändert.

Ansonsten schicke bitte mal einen Screenshot, damit ich genau weiß, was du meinst.
Grüße!

**Comment by truresma** [comment]
Sieht bei mir so aus (einige Sachen entfernt, aber Chat weiß, Anzeigennamen grell usw.)
Ich habe gar keine Namen etc. benutze Firefox
![Screenshot 2020-10-12 215114](https://user-images.githubusercontent.com/61728081/95785634-690e1f80-0cd6-11eb-8ca0-3babd82cd113.jpg)

**Comment by stonecrusher** [comment]
Hmm, da bin ich grade etwas ratlos.
Ich habe verschiedene Bildschirmgrößen, Browser und Geräte getestet, hat auch funktioniert.
Ich benutze selbst Firefox 81.0.1 und Stylus 1.5.13
Könnte sein, dass EK ein neues Design ausrollt und das nur an einem Teil der User testet. Leider kann ich es schlecht beheben, wenn ich es nicht reproduzieren kann :-/

**Comment by stonecrusher** [comment]
Hast du den Style mal neu installiert und Probleme mit anderen Addons wie DarkReader ausgeschlossen?

**Comment by truresma** [comment]
Ja, hab keine Styleaddons außer Stylus.

**Comment by stonecrusher** [comment]
Änderung ist hier angekommen, habe mal was [zusammengebastelt](https://github.com/stonecrusher/stylus-UserCSS/commit/0a1baebc33c45e53e4e5208256897a16bab351ba).
