### ISSUE TITLE
[ebay-kleinanzeigen] Some texts are too dark

### ISSUE THREAD

**Issue by Trollwut** [stonecrusher/stylus-UserCSS#9]
Since a few weeks, some texts are too dark to be recognized.

Seems like kleinanzeigen changed the class of those texts.

## Screenshot(s)
![](https://i.imgur.com/4PqbAai.png)

**Comment by stonecrusher** [comment]
Thanks for the report. Gave it [a quick fix](https://github.com/stonecrusher/stylus-UserCSS/commit/dccbe687d3f64830b9cd34e968029821a04ce263), hope it's ok already.

**Comment by Trollwut** [comment]
Thanks, automatically updated and works wonderfully! :)

**Comment by Trollwut** [comment]
Has there been changes to the code?

Because this issue is here again: Text is unreadable.

Also the link for `@homepageURL` in the head is set wrong :)

**Comment by stonecrusher** [comment]
Uh, yes.  
Again.  
But I hope the new selectors are more robust. Update to 3.8.2

Links became wrong due to github update last year... gotta check on those.

**Comment by Trollwut** [comment]
I can confirm, that it works again. Thanks for the quick response! :)
